from enum import StrEnum


class Joint(StrEnum):
    """Anatomical joint identifiers shared across model-native skeletons."""

    PELVIS = "pelvis"
    NECK = "neck"
    HEAD = "head"
    LEFT_SHOULDER = "left_shoulder"
    RIGHT_SHOULDER = "right_shoulder"
    LEFT_ELBOW = "left_elbow"
    RIGHT_ELBOW = "right_elbow"
    LEFT_WRIST = "left_wrist"
    RIGHT_WRIST = "right_wrist"
    LEFT_THUMB_CMC = "left_thumb_cmc"
    RIGHT_THUMB_CMC = "right_thumb_cmc"
    LEFT_THUMB_MCP = "left_thumb_mcp"
    RIGHT_THUMB_MCP = "right_thumb_mcp"
    LEFT_THUMB_IP = "left_thumb_ip"
    RIGHT_THUMB_IP = "right_thumb_ip"
    LEFT_INDEX_MCP = "left_index_mcp"
    RIGHT_INDEX_MCP = "right_index_mcp"
    LEFT_INDEX_PIP = "left_index_pip"
    RIGHT_INDEX_PIP = "right_index_pip"
    LEFT_INDEX_DIP = "left_index_dip"
    RIGHT_INDEX_DIP = "right_index_dip"
    LEFT_MIDDLE_MCP = "left_middle_mcp"
    RIGHT_MIDDLE_MCP = "right_middle_mcp"
    LEFT_MIDDLE_PIP = "left_middle_pip"
    RIGHT_MIDDLE_PIP = "right_middle_pip"
    LEFT_MIDDLE_DIP = "left_middle_dip"
    RIGHT_MIDDLE_DIP = "right_middle_dip"
    LEFT_RING_MCP = "left_ring_mcp"
    RIGHT_RING_MCP = "right_ring_mcp"
    LEFT_RING_PIP = "left_ring_pip"
    RIGHT_RING_PIP = "right_ring_pip"
    LEFT_RING_DIP = "left_ring_dip"
    RIGHT_RING_DIP = "right_ring_dip"
    LEFT_PINKY_MCP = "left_pinky_mcp"
    RIGHT_PINKY_MCP = "right_pinky_mcp"
    LEFT_PINKY_PIP = "left_pinky_pip"
    RIGHT_PINKY_PIP = "right_pinky_pip"
    LEFT_PINKY_DIP = "left_pinky_dip"
    RIGHT_PINKY_DIP = "right_pinky_dip"
    LEFT_HIP = "left_hip"
    RIGHT_HIP = "right_hip"
    LEFT_KNEE = "left_knee"
    RIGHT_KNEE = "right_knee"
    LEFT_ANKLE = "left_ankle"
    RIGHT_ANKLE = "right_ankle"
    LEFT_FOOT = "left_foot"
    RIGHT_FOOT = "right_foot"


__all__ = ["Joint"]
